### ISSUE TITLE
Accumulate `timers`

### ISSUE THREAD

**Issue by nelsonic** [dwyl/app-mvp-phoenix#103]
At present when we **`stop`** a **`timer`** it disappears from the UI. 🤦‍♂️
Then when we **`start`** a **`new`** one it does not reflect the previous timers (if there are any) ...
This is _obviously_ not the desired behaviour. 
What we _want_ is to:

+ [x] Display time elapsed in UI when timer stopped. #106 
+ [x] Accumulate the time elapsed (`timer.end - timer.start`) for all previous timers
+ [x] Subtract accumulated time from the _current_ **`timer.start`** so that timers **`continue`** counting.

**Comment by nelsonic** [comment]
making a stab at this now. have a decent idea of how to achieve it. 🧑‍💻 🤞 ⏳

**Comment by nelsonic** [comment]
The fun part is writing tests ... 💭

**Comment by nelsonic** [comment]
https://hexdocs.pm/elixir/1.13/Enum.html#reduce/2

**Comment by nelsonic** [comment]
```sh
  1) test accumulate timers #103 accummulate_item_timers/1 to display cummulative timer (App.TimerTest)
     test/app/timer_test.exs:41
     ** (Enum.EmptyError) empty error
     code: acc = Item.accumulate_item_timers(items_with_timers)
     stacktrace:
       (elixir 1.13.4) lib/enum.ex:2342: Enum.reduce/2
       (app 0.1.0) lib/app/item.ex:209: anonymous fn/3 in App.Item.accumulate_item_timers/1
       (elixir 1.13.4) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
       (elixir 1.13.4) lib/map.ex:236: Map.new_from_enum/2
       test/app/timer_test.exs:97: (test)
```
# 🙄

**Comment by nelsonic** [comment]
Lucky guess: used `Enum.reduce/3` instead of `Enum.reduce/2`. 🙄

**Comment by nelsonic** [comment]
I've got this working ... but it's not pretty ... 😕

**Comment by nelsonic** [comment]
But there's a test and lots of comments so it should be "refactorable" by someone smarter than me. 🤞

**Comment by nelsonic** [comment]
GIF showing a timer being started, stopped and started again:
![mvp-timer-accumulation](https://user-images.githubusercontent.com/194400/179450760-f1f8242f-a43b-42ca-8534-26e27c001a37.gif)

Obvs the disappearing timer isn't great UX. 
Let's fix that!

# GOTO: https://github.com/dwyl/app-mvp-phoenix/issues/106

**Comment by nelsonic** [comment]
Confident this is working now:
![mvp-edit-item-timer-displays-when-stopped](https://user-images.githubusercontent.com/194400/179669959-fb8696e1-fc2f-4700-8d93-604e6fc6d453.gif)

Had to port the `timer_text/2` function to `Elixir` 
cause there's a bug in `LiveView` that means 
we can only have ***one*** `Alpine.js` component in a `LiveView` page:
https://github.com/alpinejs/alpine/issues/911 🤦‍♂️ 

So server-sided rendering the _stopped_ timer.
Which I actually think makes more sense as it's ***`static`***. 👍
