### ISSUE TITLE
Deploy MVP to Fly.io! 🚀 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/app-mvp-phoenix#109]
Auth implemented. Which rounds up all the features we wanted in the MVP! 🚀 

![mvp-auth-implemented-2x-speed-full-quality](https://user-images.githubusercontent.com/194400/179797413-63e8de62-733f-4c57-a24d-7c0c662e7c46.gif)

Now it's time to _deploy_ this to Fly.io cause it's _muuuuuch_ faster than Heroku in terms of boot time. 

# Todo

+ [ ] deploy to Fly.io 🚀

**Comment by nelsonic** [comment]
Going to speed-run this now. 🧑‍💻 🚤

**Comment by nelsonic** [comment]
on `fly deploy` getting:

```sh
"/rel" not found: not found
```
Googling ... 🔍

**Comment by nelsonic** [comment]
```sh
** (Mix) You're trying to run :app on Elixir v1.13.4 but it has declared in its mix.exs file it supports only Elixir ~> 1.12.3
```
# 🤦‍♂️

**Comment by nelsonic** [comment]
This is beyond stupid. 
The error is saying I'm trying to run the app with a _later_ version of `Elixir`
than what is declared in the `mix.exs` file. What the heck man!! 🤦

**Comment by nelsonic** [comment]
Insanely, changing the line in `mix.exs` 
from:

```elixir
elixir: "~> 1.12.3",
```

to:

```elixir
elixir: "~> 1.12",
```

_Appears_ to have Worked!! 🙄

**Comment by nelsonic** [comment]
This kind of quirk drives me nuts! 🐿️

**Comment by nelsonic** [comment]
```sh
--> Building image done
==> Pushing image to fly
The push refers to repository [registry.fly.io/mvp]
c952810ebc44: Pushed
69723b258bc1: Pushed
f629d4814934: Pushed
9e8e82c5abe0: Pushed
71b1fc114005: Pushed
ba5a5fe43301: Pushed
deployment-1658309757: digest: sha256:8825729efac6aab773954759453a021d36a929f6919561ca3637b9a5e77142e4 size: 1576
--> Pushing image done
image: registry.fly.io/mvp:deployment-1658309757
image size: 119 MB
==> Creating release
--> release v2 created

--> You can detach the terminal anytime without stopping the deployment
==> Monitoring deployment

 1 desired, 1 placed, 0 healthy, 0 unhealthy [health checks: 1 total, 1 critical]
```

# ⏳

**Comment by nelsonic** [comment]
```sh
 1 desired, 1 placed, 0 healthy, 1 unhealthy [health checks: 1 total, 1 critical]
Failed Instances

Failure #1

Instance
ID      	PROCESS	VERSION	REGION	DESIRED	STATUS 	HEALTH CHECKS      	RESTARTS	CREATED
51a9f1cc	       	0      	lhr   	run    	running	1 total, 1 critical	0       	4m54s ago

Recent Events
TIMESTAMP           	TYPE      	MESSAGE
2022-07-20T09:38:18Z	Received  	Task received by client
2022-07-20T09:38:18Z	Task Setup	Building Task Directory
2022-07-20T09:38:29Z	Started   	Task started by client

2022-07-20T09:38:24Z   [info]Starting instance
2022-07-20T09:38:24Z   [info]Configuring virtual machine
2022-07-20T09:38:24Z   [info]Pulling container image
2022-07-20T09:38:26Z   [info]Unpacking image
2022-07-20T09:38:28Z   [info]Preparing kernel init
2022-07-20T09:38:29Z   [info]Configuring firecracker
2022-07-20T09:38:29Z   [info]Starting virtual machine
2022-07-20T09:38:29Z   [info]Starting init (commit: c86b3dc)...
2022-07-20T09:38:29Z   [info]Preparing to run: `/bin/sh -c /app/bin/server` as nobody
2022-07-20T09:38:29Z   [info]2022/07/20 09:38:29 listening on [fdaa:0:78d4:a7b:bbfa:51a9:f1cc:2]:22 (DNS: [fdaa::3]:53)
2022-07-20T09:38:30Z   [info]Reaped child process with pid: 552, exit code: 0
2022-07-20T09:38:32Z   [info]09:38:32.426 [info] Running AppWeb.Endpoint with cowboy 2.9.0 at :::4000 (http)
2022-07-20T09:38:32Z   [info]09:38:32.428 [info] Access AppWeb.Endpoint at https://example.com
2022-07-20T09:38:32Z   [info]Reaped child process with pid: 574 and signal: SIGUSR1, core dumped? false
--> v0 failed - Failed due to unhealthy allocations - no stable job version to auto revert to and deploying as v1

--> Troubleshooting guide at https://fly.io/docs/getting-started/troubleshooting/
Error abort
```

Lame. 🤦‍♂️

**Comment by nelsonic** [comment]
```sh
==> Creating release
--> release v2 created

--> You can detach the terminal anytime without stopping the deployment
==> Release command detected: /app/bin/migrate

--> This release will not be available until the release command succeeds.
	 Starting instance
	 Configuring virtual machine
	 Pulling container image
	 Unpacking image
	 Preparing kernel init
	 Configuring firecracker
	 Starting virtual machine
	 Starting init (commit: c86b3dc)...
	 Setting up swapspace version 1, size = 512 MiB (536866816 bytes)
	 no label, UUID=c915231d-eb25-4d27-89b5-45bfe988eeb5
	 Preparing to run: `/app/bin/migrate` as nobody
	 2022/07/20 10:05:54 listening on [fdaa:0:78d4:a7b:bada:ae39:8035:2]:22 (DNS: [fdaa::3]:53)
	 10:05:57.058 [info] == Running 20220627162148 App.Repo.Migrations.CreatePeople.change/0 forward
	 10:05:57.062 [info] create table people
	 10:05:57.078 [info] == Migrated 20220627162148 in 0.0s
	 10:05:57.130 [info] == Running 20220627162154 App.Repo.Migrations.CreateItems.change/0 forward
	 10:05:57.130 [info] create table items
	 10:05:57.135 [info] create index items_person_id_index
	 10:05:57.144 [info] create index timers_item_id_index
	 10:05:57.145 [info] create index timers_person_id_index
	 10:05:57.147 [info] == Migrated 20220627162209 in 0.0s
	 Main child exited normally with code: 0
	 Starting clean up.
	 Starting instance
	 Configuring virtual machine
	 Pulling container image
	 Unpacking image
	 Preparing kernel init
	 Configuring firecracker
	 Starting virtual machine
	 Starting init (commit: c86b3dc)...
	 Setting up swapspace version 1, size = 512 MiB (536866816 bytes)
	 no label, UUID=c915231d-eb25-4d27-89b5-45bfe988eeb5
	 Preparing to run: `/app/bin/migrate` as nobody
	 2022/07/20 10:05:54 listening on [fdaa:0:78d4:a7b:bada:ae39:8035:2]:22 (DNS: [fdaa::3]:53)
	 10:05:57.058 [info] == Running 20220627162148 App.Repo.Migrations.CreatePeople.change/0 forward
	 10:05:57.062 [info] create table people
	 10:05:57.078 [info] == Migrated 20220627162148 in 0.0s
	 10:05:57.130 [info] == Running 20220627162154 App.Repo.Migrations.CreateItems.change/0 forward
	 10:05:57.130 [info] create table items
	 10:05:57.135 [info] create index items_person_id_index
	 10:05:57.137 [info] == Migrated 20220627162154 in 0.0s
	 10:05:57.140 [info] == Running 20220627162209 App.Repo.Migrations.CreateTimers.change/0 forward
	 10:05:57.141 [info] create table timers
	 10:05:57.144 [info] create index timers_item_id_index
	 10:05:57.145 [info] create index timers_person_id_index
	 10:05:57.147 [info] == Migrated 20220627162209 in 0.0s
	 Main child exited normally with code: 0
	 Reaped child process with pid: 568 and signal: SIGUSR1, core dumped? false
	 Starting clean up.
==> Monitoring deployment

 1 desired, 1 placed, 1 healthy, 0 unhealthy [health checks: 1 total, 1 passing]
--> v2 deployed successfully
```

But ... https://mvp.fly.dev/
![image](https://user-images.githubusercontent.com/194400/179956685-86840907-394f-43dc-9546-271b993af7a6.png)

So gotta figure out the assets. 🙄

**Comment by nelsonic** [comment]
Also: https://mvp.fly.dev/login
![image](https://user-images.githubusercontent.com/194400/179958111-bd33ca5f-bb99-4f35-9113-3fb2641aff91.png)

So on the whole not a very successful deployment ... yet! ⏳

**Comment by nelsonic** [comment]
scrapped the `fly.toml` and `Dockerfiles` and did a fresh `fly launch` ... ⏳

**Comment by nelsonic** [comment]
This is a DNS cache on my _local_ network. 🤦‍♂️ 
Works for @SimonLab ...
So I tried it on my phone (4G not Wifi!) and it worked.
But not auth ...
still get the internal server error. 
need to investigate that now.

**Comment by nelsonic** [comment]
```sh
fly logs
```

```sh
2022-07-20T10:45:32Z app[f754a22b] lhr [info]Server: mvp.fly.dev:80 (http)
2022-07-20T10:45:32Z app[f754a22b] lhr [info]Request: GET /login
2022-07-20T10:45:32Z app[f754a22b] lhr [info]** (exit) an exception was raised:
2022-07-20T10:45:32Z app[f754a22b] lhr [info]    ** (FunctionClauseError) no function clause matching in Regex.run/3
2022-07-20T10:45:32Z app[f754a22b] lhr [info]        (elixir 1.13.4) lib/regex.ex:324: Regex.run(~r/^(.*)\/(.*)\/(.*)$/, nil, [])
2022-07-20T10:45:32Z app[f754a22b] lhr [info]        (auth_plug 1.4.13) lib/token.ex:58: AuthPlug.Token.auth_url/0
2022-07-20T10:45:32Z app[f754a22b] lhr [info]        (auth_plug 1.4.13) lib/auth_plug.ex:153: AuthPlug.get_auth_url/2
2022-07-20T10:45:32Z app[f754a22b] lhr [info]        (app 1.0.0) lib/app_web/controllers/auth_controller.ex:28: AppWeb.AuthController.login/2
2022-07-20T10:45:32Z app[f754a22b] lhr [info]        (app 1.0.0) lib/app_web/controllers/auth_controller.ex:1: AppWeb.AuthController.action/2
2022-07-20T10:45:32Z app[f754a22b] lhr [info]        (app 1.0.0) lib/app_web/controllers/auth_controller.ex:1: AppWeb.AuthController.phoenix_controller_pipeline/2
2022-07-20T10:45:32Z app[f754a22b] lhr [info]        (phoenix 1.6.11) lib/phoenix/router.ex:354: Phoenix.Router.__call__/2
2022-07-20T10:45:32Z app[f754a22b] lhr [info]        (app 1.0.0) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.plug_builder_call/2
```

Why?! 🤷‍♂️ 
The `AUTH_API_KEY` is configured! 😖

**Comment by nelsonic** [comment]
@SimonLab please confirm you have access to: https://fly.io/apps/mvp thanks. 👍

**Comment by SimonLab** [comment]
I think the error is due to the configuration in `auth_plug`, specifically the way the `api_key` is retrieved:

```elixir
  def api_key do
    Application.fetch_env!(:auth_plug, :api_key)
  end

  #  The regex group the 3 part of the env (id, secret and auth_url)
  #  - (.*) match any characters multiple time
  #  - \/ escape the /

  defp split_env() do
    Regex.run(~r/^(.*)\/(.*)\/(.*)$/, api_key())
  end
```

We might want to use `System.get_env` instead of `Application.fetch_env` as the config file of dependencies are not used

see https://hexdocs.pm/elixir/1.12/Config.html
>Important: if you are writing a library to be used by other developers, it is generally recommended to avoid the application environment, as the application environment is effectively a global storage. Also note that the config/config.exs of a library is not evaluated when the library is used as a dependency, as configuration is always meant to configure the current project. For more information, read our [library guidelines](https://hexdocs.pm/elixir/1.12/library-guidelines.html).

**Comment by nelsonic** [comment]
Detour: #110

**Comment by nelsonic** [comment]
@SimonLab -> https://github.com/dwyl/auth_plug/pull/66 🙏

**Comment by nelsonic** [comment]
Now we can get to `auth.dwyl.com` but when we return to the MVP app we see the following:
![image](https://user-images.githubusercontent.com/194400/179980541-1c6d3349-b358-4426-b8ec-75ee2da32462.png)


`fly logs`:
```sh
2022-07-20T12:18:24Z app[a8126641] lhr [info]Server: mvp.fly.dev:80 (http)
2022-07-20T12:18:24Z app[a8126641] lhr [info]Request: GET /?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBfaWQiOjgsImF1dGhfcHJvdmlkZXIiOiJnaXRodWIiLCJlbWFpbCI6Im5lbHNvbitnaXRodWJAZHd5bC5jb20iLCJnaXZlbk5hbWUiOiJOZWxzb24iLCJpZCI6MiwicGljdHVyZSI6Imh0dHBzOi8vYXZhdGFycy5naXRodWJ1c2VyY29udGVudC5jb20vdS8xOTQ0MDA_dj00Iiwicm9sZXMiOiI2LDYiLCJzaWQiOjE0NCwic3RhdHVzIjoxLCJhdWQiOiJKb2tlbiIsImV4cCI6MTY4OTg1NjUwNCwiaWF0IjoxNjU4MzE5NTA0LCJpc3MiOiJKb2tlbiIsImp0aSI6IjJzMW9oamNqcjdiNmg5Z2ZnazAwMDJhMSIsIm5iZiI6MTY1ODMxOTUwNH0.Q-wh_Q--wcWoQmHmoqZJbcG_mkX5ZEOahPuScVFL6ns
2022-07-20T12:18:24Z app[a8126641] lhr [info]** (exit) an exception was raised:
2022-07-20T12:18:24Z app[a8126641] lhr [info]    ** (FunctionClauseError) no function clause matching in String.replace/4
2022-07-20T12:18:24Z app[a8126641] lhr [info]        (elixir 1.13.4) lib/string.ex:1477: String.replace(nil, "'", "", [])
2022-07-20T12:18:24Z app[a8126641] lhr [info]        (fields 2.9.0) lib/aes.ex:91: Fields.AES.fetch_keys/0
2022-07-20T12:18:24Z app[a8126641] lhr [info]        (fields 2.9.0) lib/aes.ex:69: Fields.AES.get_key_id/0
2022-07-20T12:18:24Z app[a8126641] lhr [info]        (fields 2.9.0) lib/aes.ex:34: Fields.AES.encrypt/1
2022-07-20T12:18:24Z app[a8126641] lhr [info]        (fields 2.9.0) lib/encrypted.ex:21: Fields.Encrypted.dump/1
2022-07-20T12:18:24Z app[a8126641] lhr [info]        (ecto 3.8.4) lib/ecto/type.ex:938: Ecto.Type.process_dumpers/3
2022-07-20T12:18:24Z app[a8126641] lhr [info]        (ecto 3.8.4) lib/ecto/repo/schema.ex:996: Ecto.Repo.Schema.dump_field!/6
2022-07-20T12:18:24Z app[a8126641] lhr [info]        (ecto 3.8.4) lib/ecto/repo/schema.ex:1009: anonymous fn/6 in Ecto.Repo.Schema.dump_fields!/5
2022-07-20T12:18:50Z app[a8126641] lhr [info]12:18:50.271 [info] CONNECTED TO Phoenix.LiveView.Socket in 37µs
2022-07-20T12:18:50Z app[a8126641] lhr [info]  Transport: :websocket
2022-07-20T12:18:50Z app[a8126641] lhr [info]  Serializer: Phoenix.Socket.V2.JSONSerializer
2022-07-20T12:18:50Z app[a8126641] lhr [info]  Parameters: %{"_csrf_token" => "YEk-QXAiIi1KBQ1CDVQPG1YZDmcUFBViMxh7GsDWzcyvxmWtoaeJaYB7", "_mounts" => "1", "_track_static" => %{"0" => "https://mvp.fly.dev/assets/app-8a5053b9d36bf6be1bd316e21f8f3b9b.css?vsn=d", "1" => "https://mvp.fly.dev/assets/app-da072adf50afc600b155f8e9e5bd1d00.js?vsn=d"}, "vsn" => "2.0.0"}
2022-07-20T12:18:50Z app[a8126641] lhr [info]12:18:50.316 [debug] QUERY OK db=1.1ms queue=1.4ms idle=1193.7ms
2022-07-20T12:18:50Z app[a8126641] lhr [info]SELECT i.id, i.text, i.status_code, i.person_id, t.start, t.end, t.id as timer_id FROM items i
2022-07-20T12:18:50Z app[a8126641] lhr [info]FULL JOIN timers as t ON t.item_id = i.id
2022-07-20T12:18:50Z app[a8126641] lhr [info]WHERE i.person_id = $1 AND i.status_code IS NOT NULL AND i.status_code != 6
2022-07-20T12:18:50Z app[a8126641] lhr [info]ORDER BY timer_id ASC;
2022-07-20T12:18:50Z app[a8126641] lhr [info] [1]
```

https://github.com/dwyl/fields/blob/55cd179c8f8991b3b8dd3577d9b89267f976f977/lib/aes.ex#L89 🙄

**Comment by nelsonic** [comment]
@SimonLab -> https://github.com/dwyl/fields/pull/109 🙏

**Comment by nelsonic** [comment]
https://mvp.fly.dev/ 🚀 
![image](https://user-images.githubusercontent.com/194400/179984838-3deea91f-ee73-47e8-8707-9a1e837c3719.png)

**Comment by nelsonic** [comment]
`FLY_API_TOKEN` added to: https://github.com/dwyl/app-mvp-phoenix/settings/secrets/actions ✅  🚀
