### ISSUE TITLE
** (ErlangError) Erlang error: {:badarg, {'aead.c', 90}, 'Unknown cipher or invalid key size'}

### ISSUE THREAD

**Issue by nelsonic** [dwyl/app-mvp-phoenix#92]
https://github.com/dwyl/app-mvp-phoenix/runs/7276485713?check_suite_focus=true#step:7:173
![image](https://user-images.githubusercontent.com/194400/178194370-a2d91dd6-00f3-46a2-a5a5-d646daada235.png)

```sh
** (ErlangError) Erlang error: {:badarg, {'aead.c', 90}, 'Unknown cipher or invalid key size'}
    (crypto 5.1) crypto.erl:982: :crypto.crypto_one_time_aead(:aes_256_gcm, "", <<34, 41, 227, 244, 55, 153, 210, 169, 201, 246, 127, 207, 37, 31, 38, 23>>, "Beyoncé", "AES256GCM", 16, true)
    (fields 2.9.0) lib/aes.ex:36: Fields.AES.encrypt/1
    (fields 2.9.0) lib/encrypted.ex:21: Fields.Encrypted.dump/1
    (ecto 3.8.4) lib/ecto/type.ex:938: Ecto.Type.process_dumpers/3
    (ecto 3.8.4) lib/ecto/repo/schema.ex:996: Ecto.Repo.Schema.dump_field!/6
    (ecto 3.8.4) lib/ecto/repo/schema.ex:1009: anonymous fn/6 in Ecto.Repo.Schema.dump_fields!/5
    (stdlib 4.0) maps.erl:411: :maps.fold_1/3
    (ecto 3.8.4) lib/ecto/repo/schema.ex:1007: Ecto.Repo.Schema.dump_fields!/5
```

Debugging this ...

**Comment by nelsonic** [comment]
Created `ENCRYPTION_KEYS` repository secret:
https://github.com/dwyl/app-mvp-phoenix/settings/secrets/actions
![image](https://user-images.githubusercontent.com/194400/178194771-c68f292b-e197-4148-be8f-0ce0b408b859.png)

Re-running the failed build. 🤞

**Comment by nelsonic** [comment]
https://github.com/dwyl/app-mvp-phoenix/runs/7276558309?check_suite_focus=true#step:7:177
![image](https://user-images.githubusercontent.com/194400/178195217-c9790e15-4b67-4e0d-86f3-137a78324f1a.png)

Fixed. ✅
